spring:
  application:
    name: ingestion-service
  data:
    redis:
      host: localhost
      port: 6379

  kafka:
    topic:
      transactions-raw: transactions.raw
    bootstrap-servers: localhost:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
